### ISSUE TITLE
RegExp.compile("^[a-z][a-z0-9]*$", "i")  leads to NPE

### ISSUE THREAD

**Issue by treblereel** [gwtproject/gwt-regexp#2] opened 2019-07-25 18:22 UTC
Error in console.log:
Uncaught TypeError: Cannot read property 'm_compile__java_lang_String__java_lang_String' of null

Thanks for any help !

**Comment by FrankHossfeld** [comment] 2019-10-13 11:18
Tried to reproduce, but was not able. Can you provide more informations please.

**Comment by niloc132** [comment] 2020-02-17 17:13
Closing this, looks like it could have been an early j2cl-maven-plugin error with dependencies not being present.

**Closed as completed by niloc132** 2020-02-17 17:13 UTC
